import json
import os
import math
from datetime import datetime

# --- CONFIGURATION ---
INPUT_FILE = "dscovr_raw.json"  # The file downloaded by your workflow
OUTPUT_DIR = "measurements/events"
CHI_LIMIT = 0.15

def calculate_stats(rows):
    """
    Parses raw NOAA data (List of Lists) and calculates Imperial Chi.
    Format: [time, density, speed, temp]
    """
    # Extract Speed values (Index 2), filtering out invalid data
    speeds = []
    valid_rows = []
    
    for row in rows[1:]: # Skip header
        try:
            speed = float(row[2])
            if speed > 0:
                speeds.append(speed)
                valid_rows.append(row)
        except (ValueError, IndexError):
            continue

    if not speeds:
        return None

    # Calculate Imperial Baseline (Median)
    speeds.sort()
    mid = len(speeds) // 2
    median_speed = speeds[mid]
    
    # Calculate Max Chi
    # Chi = |Current - Median| / Median
    max_chi = 0.0
    violations = 0
    
    for v in speeds:
        chi = abs(v - median_speed) / (median_speed + 1e-9)
        if chi > max_chi:
            max_chi = chi
        if chi > CHI_LIMIT:
            violations += 1
            
    return {
        "max_chi": max_chi,
        "mean_chi": sum(speeds) / len(speeds), # storing avg speed as proxy for now
        "violations": violations,
        "median_baseline": median_speed,
        "count": len(speeds)
    }

def get_harmonic_mode(chi):
    if chi <= CHI_LIMIT: return 1
    return int(chi / CHI_LIMIT) + 1

def main():
    if not os.path.exists(INPUT_FILE):
        print(f"Skipping: {INPUT_FILE} not found (workflow pending).")
        return

    with open(INPUT_FILE, "r") as f:
        raw_data = json.load(f)

    stats = calculate_stats(raw_data)
    if not stats:
        print("No valid data found.")
        return

    # Generate Report
    mode = get_harmonic_mode(stats['max_chi'])
    timestamp = datetime.utcnow().isoformat()
    
    # Only report if there is noteworthy activity (Mode > 1) OR for daily logs
    # For now, we log everything to verify operation.
    
    filename = f"{OUTPUT_DIR}/{timestamp.split('T')[0]}-mode-{mode}.md"
    
    content = f"""# ⚡ Imperial Automated Log
**Date:** {timestamp}
**Harmonic Mode:** {mode}

| Metric | Value |
| :--- | :--- |
| **Max $\chi$** | `{stats['max_chi']:.5f}` |
| **Violations** | `{stats['violations']}` |
| **Baseline Speed** | `{stats['median_baseline']:.1f} km/s` |
| **Status** | {"🟢 Nominal" if mode == 1 else "🔴 **REGULATOR ACTIVE**"} |

*Generated by LUFT-Portal*
"""

    os.makedirs(OUTPUT_DIR, exist_ok=True)
    with open(filename, "w") as f:
        f.write(content)
    
    print(f"Report generated: {filename}")

if __name__ == "__main__":
    main()
