#!/usr/bin/env python3
"""
NSVS Direct ASAS-SN Query Script

This script queries ASAS-SN data via VizieR using astroquery without requiring pyasassn.
It retrieves catalog metadata for the Schmidt "Dipper" stars and generates instructions
for manual light curve download.

Workaround for pyasassn installation failure - uses astroquery VizieR for catalog lookup,
then provides manual download instructions for full light curves.

IMPORTANT: VizieR only provides catalog metadata (average magnitudes, positions, etc.).
For full time-series light curves, use the manual download instructions generated by this script.
"""

import json
import os
from datetime import datetime, timezone

try:
    from astroquery.vizier import Vizier
    from astropy.coordinates import SkyCoord
    import astropy.units as u
    ASTROQUERY_AVAILABLE = True
except ImportError:
    ASTROQUERY_AVAILABLE = False
    print("ERROR: astroquery not available. Install with: pip install astroquery")
    print("This is required for querying ASAS-SN data via VizieR.")
    exit(1)

def query_asassn_vizier(ra, dec, radius=2.5):
    """
    Query ASAS-SN data via VizieR mirror using astroquery.
    
    Args:
        ra: Right Ascension (degrees)
        dec: Declination (degrees)
        radius: Search radius (arcminutes, default 2.5)
    
    Returns:
        dict: Dictionary with keys 'source', 'num_sources', 'data' containing catalog
              metadata, or None if query fails or no sources found
    """
    try:
        print(f"    Querying VizieR for ASAS-SN data: RA={ra:.5f}, Dec={dec:.5f}, radius={radius}'")
        
        # Create coordinate object
        coord = SkyCoord(ra=ra*u.deg, dec=dec*u.deg, frame='icrs')
        
        # Query VizieR for ASAS-SN catalog (II/366 is ASAS-SN Variable Stars Database)
        # Use reasonable limit since cone searches should return few results
        v = Vizier(columns=['all'], row_limit=100)
        result = v.query_region(coord, radius=radius*u.arcmin, catalog='II/366')
        
        if result and len(result) > 0:
            # Convert astropy table to dict for JSON serialization
            table = result[0]
            print(f"    ✓ Found {len(table)} sources in VizieR")
            
            # Convert table to list of dicts
            data = []
            for row in table:
                row_dict = {}
                for col in table.colnames:
                    val = row[col]
                    # Convert masked values and numpy types to Python types
                    if hasattr(val, 'mask') and val.mask:
                        row_dict[col] = None
                    elif hasattr(val, 'item'):
                        row_dict[col] = val.item()
                    else:
                        row_dict[col] = val
                data.append(row_dict)
            
            return {
                'source': 'VizieR II/366 (ASAS-SN Variable Stars)',
                'num_sources': len(table),
                'data': data
            }
        else:
            print(f"    ✗ No sources found in VizieR")
            return None
            
    except Exception as e:
        print(f"    ✗ VizieR Query Error: {e}")
        return None


def convert_deg_to_hms_dms(ra_deg, dec_deg):
    """
    Convert decimal degree coordinates to HMS/DMS format.
    
    Args:
        ra_deg: Right Ascension in decimal degrees
        dec_deg: Declination in decimal degrees
    
    Returns:
        tuple: (ra_h, ra_m, ra_s, dec_sign, dec_d, dec_m, dec_s)
    """
    # Convert RA to HMS
    ra_h = int(ra_deg / 15)
    ra_m = int((ra_deg / 15 - ra_h) * 60)
    ra_s = ((ra_deg / 15 - ra_h) * 60 - ra_m) * 60
    
    # Convert Dec to DMS
    dec_sign = '+' if dec_deg >= 0 else '-'
    dec_d = int(abs(dec_deg))
    dec_m = int((abs(dec_deg) - dec_d) * 60)
    dec_s = ((abs(dec_deg) - dec_d) * 60 - dec_m) * 60
    
    return ra_h, ra_m, ra_s, dec_sign, dec_d, dec_m, dec_s

# Target coordinates (from nsvs_beacon_chain_scanner.py)
targets = {
    'NSVS 2354429': {'ra': 240.25563, 'dec': 27.61100},
    'NSVS 2913753': {'ra': 307.87533, 'dec': 41.21147},
    'NSVS 3037513': {'ra': 308.37521, 'dec': 41.32047},
    'NSVS 6804071': {'ra': 304.87933, 'dec': 41.54903},
    'NSVS 6814519': {'ra': 305.00079, 'dec': 41.71017},
    'NSVS 7255468': {'ra': 306.44008, 'dec': 41.66428},
    'NSVS 7575062': {'ra': 307.88392, 'dec': 41.80644},
    'NSVS 7642696': {'ra': 308.23404, 'dec': 41.65069}
}

def main():
    """Execute ASAS-SN VizieR queries for all NSVS targets"""
    
    print("="*70)
    print("NSVS ASAS-SN QUERY MISSION (via VizieR/astroquery)")
    print("="*70)
    print(f"Timestamp: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S')} UTC")
    print(f"Total Targets: {len(targets)}")
    print(f"Method: VizieR catalog II/366 (ASAS-SN Variable Stars)")
    print(f"astroquery available: {ASTROQUERY_AVAILABLE}")
    print("="*70)
    print()
    
    # Run queries
    results = {}
    successful_queries = 0
    failed_queries = 0
    catalog_matches = []
    
    for name, coords in targets.items():
        print(f"TARGET: {name}")
        print(f"  Coordinates: RA={coords['ra']:.5f}°, Dec={coords['dec']:.5f}°")
        
        data = query_asassn_vizier(coords['ra'], coords['dec'])
        
        if data:
            results[name] = {
                'coordinates': coords,
                'vizier_data': data,
                'query_time': datetime.now(timezone.utc).isoformat()
            }
            print(f"  ✓ Catalog metadata retrieved")
            
            # Extract ASAS-SN ID if available
            if data.get('data') and len(data['data']) > 0:
                asassn_id = data['data'][0].get('ASASSN-V', 'Unknown')
                catalog_matches.append({
                    'name': name,
                    'asassn_id': asassn_id,
                    'ra': coords['ra'],
                    'dec': coords['dec']
                })
                print(f"    ASAS-SN ID: {asassn_id}")
            
            successful_queries += 1
        else:
            results[name] = {
                'coordinates': coords,
                'vizier_data': None,
                'error': 'Not in VizieR catalog - manual lookup required',
                'query_time': datetime.now(timezone.utc).isoformat()
            }
            print(f"  ✗ Not found in catalog - manual download needed")
            failed_queries += 1
        
        print()
    
    # Summary
    print("="*70)
    print("QUERY MISSION COMPLETE")
    print("="*70)
    print(f"Catalog Metadata Retrieved: {successful_queries}/{len(targets)}")
    print(f"Manual Download Required: {failed_queries}/{len(targets)}")
    print()
    
    # Generate manual download instructions
    print("="*70)
    print("MANUAL LIGHT CURVE DOWNLOAD INSTRUCTIONS")
    print("="*70)
    print()
    print("VizieR only provides catalog metadata, not full time-series light curves.")
    print("To get complete light curve data for beacon analysis, follow these steps:")
    print()
    print("1. Go to: https://asas-sn.osu.edu/photometry")
    print()
    print("2. For each target below, enter the coordinates and download the CSV:")
    print()
    
    for name, coords in targets.items():
        ra_h, ra_m, ra_s, dec_sign, dec_d, dec_m, dec_s = convert_deg_to_hms_dms(coords['ra'], coords['dec'])
        
        print(f"   {name}:")
        print(f"     RA:  {ra_h:02d} {ra_m:02d} {ra_s:05.2f}  ({coords['ra']:.5f}°)")
        print(f"     Dec: {dec_sign}{dec_d:02d} {dec_m:02d} {dec_s:05.2f}  ({dec_sign}{abs(coords['dec']):.5f}°)")
        print(f"     → Save as: data/beacon_scan/manual/{name.replace(' ', '_').lower()}_lightcurve.csv")
        print()
    
    print("3. After downloading all CSV files, run beacon analysis on the data.")
    print()
    print("="*70)
    
    # Save results
    output_dir = "data/beacon_scan"
    manual_dir = f"{output_dir}/manual"
    os.makedirs(output_dir, exist_ok=True)
    os.makedirs(manual_dir, exist_ok=True)
    
    timestamp = datetime.now(timezone.utc).strftime('%Y%m%d_%H%M%S')
    
    # Save catalog metadata
    catalog_file = f'{output_dir}/asassn_catalog_{timestamp}.json'
    with open(catalog_file, 'w') as f:
        json.dump({
            'query_time': datetime.now(timezone.utc).isoformat(),
            'method': 'VizieR astroquery (catalog II/366)',
            'note': 'This contains catalog metadata only. Download full light curves manually.',
            'targets_queried': len(targets),
            'successful_queries': successful_queries,
            'failed_queries': failed_queries,
            'results': results
        }, f, indent=2)
    
    print(f"Catalog metadata saved to: {catalog_file}")
    
    # Save download instructions
    instructions_file = f'{output_dir}/MANUAL_DOWNLOAD_INSTRUCTIONS.txt'
    with open(instructions_file, 'w') as f:
        f.write("="*70 + "\n")
        f.write("ASAS-SN MANUAL LIGHT CURVE DOWNLOAD INSTRUCTIONS\n")
        f.write("="*70 + "\n\n")
        f.write("Generated: " + datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S') + " UTC\n\n")
        f.write("BACKGROUND:\n")
        f.write("The pyasassn library cannot be installed due to compilation issues.\n")
        f.write("VizieR only provides catalog metadata, not full time-series data.\n")
        f.write("Therefore, light curves must be downloaded manually from ASAS-SN.\n\n")
        f.write("STEP-BY-STEP INSTRUCTIONS:\n\n")
        f.write("1. Navigate to: https://asas-sn.osu.edu/photometry\n\n")
        f.write("2. For each target listed below:\n")
        f.write("   a. Enter the RA and Dec coordinates (in HMS/DMS format)\n")
        f.write("   b. Click 'Compute'\n")
        f.write("   c. Wait for light curve to generate\n")
        f.write("   d. Click 'CSV' button to download\n")
        f.write("   e. Save file to the location specified\n\n")
        f.write("3. TARGET COORDINATES:\n\n")
        
        for name, coords in targets.items():
            ra_h, ra_m, ra_s, dec_sign, dec_d, dec_m, dec_s = convert_deg_to_hms_dms(coords['ra'], coords['dec'])
            
            f.write(f"   {name}:\n")
            f.write(f"     RA:  {ra_h:02d} {ra_m:02d} {ra_s:05.2f}\n")
            f.write(f"     Dec: {dec_sign}{dec_d:02d} {dec_m:02d} {dec_s:05.2f}\n")
            f.write(f"     Save to: data/beacon_scan/manual/{name.replace(' ', '_').lower()}_lightcurve.csv\n\n")
        
        f.write("4. AFTER DOWNLOADING:\n")
        f.write("   Run the beacon network analysis on the downloaded CSV files.\n")
        f.write("   The analysis will look for pulse signatures matching NSVS 2354429.\n\n")
        f.write("="*70 + "\n")
    
    print(f"Instructions saved to: {instructions_file}")
    print("="*70)
    
    return results

if __name__ == "__main__":
    main()
