name: GOES Data Audit — Robust & Friendly

on:
  schedule:
    - cron: "7 * * * *"
  workflow_dispatch:

jobs:
  audit-goes-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Prepare data storage folders
        run: |
          mkdir -p data
          mkdir -p data/goes

      - name: Download GOES JSON (with detailed error handling)
        run: |
          curl -s -o data/goes/latest_goes_flux.json https://services.swpc.noaa.gov/products/goes-xray-flux.json
          CURL_STATUS=$?
          if [ $CURL_STATUS -ne 0 ]; then
            echo "ERROR: curl failed with exit code $CURL_STATUS"
            exit 23
          fi
          if ! jq . data/goes/latest_goes_flux.json > /dev/null; then
            echo "ERROR: Downloaded file is invalid JSON!"
            head data/goes/latest_goes_flux.json
            exit 24
          fi

      - name: Parse latest GOES event (safer)
        run: |
          jq '.[-1]' data/goes/latest_goes_flux.json > data/goes/goes_event_audit.json
          if ! jq . data/goes/goes_event_audit.json > /dev/null; then
            echo "ERROR: Audit file is invalid JSON!"
            cat data/goes/goes_event_audit.json
            exit 25
          fi

      - name: Configure Git (needed in GitHub Actions)
        run: |
          git config --global user.email "auto@luft-portal"
          git config --global user.name "LUFT-bot"

      - name: Pull latest main before commit (prevents non-fast-forward errors)
        run: |
          git pull --rebase origin main

      - name: Commit event audit on safe branch (avoids push conflicts)
        run: |
          git checkout -b update-goes-audit || git checkout update-goes-audit
          git add data/goes/goes_event_audit.json
          git commit -m "GOES event audit JSON, validated"
          git push origin update-goes-audit

      - name: PR suggestion (instructions only)
        run: echo "Open a PR from update-goes-audit to main. Review and merge in GitHub UI!"
