name: Imperial Sentinel (Daily Vacuum Audit)

# 1. THE TRIGGERS
on:
  schedule:
    # Runs automatically at 00:00 and 12:00 UTC every day
    - cron: '0 0,12 * * *'
  workflow_dispatch: 
    # Adds a "Run workflow" button in GitHub so you can fire it manually anytime

# 2. THE SERVER SPECIFICATIONS
jobs:
  vacuum_audit:
    runs-on: ubuntu-latest
    
    steps:
      # Step A: Boot up the repository
      - name: Checkout Imperial Repository
        uses: actions/checkout@v4

      # Step B: Install the Python Engine
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Step C: Install the Imperial Toolkit
      - name: Install Physics Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uproot awkward numpy requests

      # Step D: Install the CERN XRootD Protocol 
      # (This is the master key to bypass the HTML blockades)
      - name: Install XRootD Client
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y xrootd-client

      # Step E: Execute the Probes
      # This points to a python file we will put in your repo
      - name: Execute Multi-Sector Vacuum Scan
        run: python automated_probes.py

      # Step F: (Optional) Save the results to an artifact log
      - name: Archive Imperial Readout
        uses: actions/upload-artifact@v4
        with:
          name: vacuum-state-logs
          path: '*.txt'
