name: Imperial Lattice Observatory
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 * * * *' # Runs every hour to catch the instantaneous shifts

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Imperial Tools
        run: pip install astroquery astropy requests
      - name: Run Metric Interrogation
        run: python audit_spheres.py
