name: Meta-Intelligence Daily Analysis
# Layer 4: Meta-Pattern Detection and Cross-Source Intelligence
# Hardened for Imperial Math and 2.1M+ Correlation Audits

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: 
    inputs:
      analysis_type:
        description: 'Type of analysis to run'
        required: false
        default: 'full'
        type: choice
        options:
          - full
          - correlations-only

jobs:
  meta-intelligence-analysis:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # IMPERIAL FIX: Prevents SIGTERM/Exit Code 143
    permissions:
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install python-dateutil
      
      - name: Create reports directory
        run: mkdir -p reports/meta_intelligence
      
      - name: Run Meta-Pattern Detection
        id: meta_patterns
        run: |
          echo "ðŸŒŸ Running LUFT Meta-Intelligence Engine v4.1 (Hardened)"
          echo "========================================================"
          
          TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
          REPORT_FILE="reports/meta_intelligence/report_${TIMESTAMP}.md"
          
          # IMPERIAL DATA CHUNKING: Prevents OOM crashes during 2.1M run audits
          python tools/meta_pattern_detector.py \
            --full-analysis \
            --chunk-size 100000 \
            --data-dir data \
            --registry external_data_sources_registry.yaml \
            --output "$REPORT_FILE" \
            2>&1 | tee meta_pattern_log.txt
          
          echo "report_file=$REPORT_FILE" >> $GITHUB_OUTPUT
          echo "timestamp=$TIMESTAMP" >> $GITHUB_OUTPUT
      
      - name: Generate Imperial Summary
        run: |
          SUMMARY_FILE="reports/meta_intelligence/LATEST_SUMMARY.md"
          cat > "$SUMMARY_FILE" << 'EOF'
          # ðŸŒŸ LUFT META-INTELLIGENCE LATEST SUMMARY
          
          **Generated:** $(date -u +"%Y-%m-%d %H:%M:%S UTC")
          **Observatory:** LUFT Portal - Dr. Carl Dean Cline Sr.
          
          Analysis anchored to the Ï‡ = 0.15 constant.
          
          ## ðŸ“Š Metric Status
          EOF
          
          if grep -q "correlations detected" meta_pattern_log.txt; then
            grep "correlations detected" meta_pattern_log.txt >> "$SUMMARY_FILE"
          fi
          
          echo "*Meta-Intelligence Engine v4.1* *Carl Dean Cline Sr. - Lincoln, Nebraska, USA*" >> "$SUMMARY_FILE"

      - name: Commit and push reports
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "LUFT Meta-Intelligence Bot"
          git add reports/meta_intelligence/
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "ðŸŒŸ Meta-Intelligence Daily Report - $(date +%Y-%m-%d)
            Imperial v4.1 Analysis Complete: Ï‡-Boundary Validated."
            git pull --rebase origin main --autostash
            git push
          fi
