from pathlib import Path
import json
import sys

import numpy as np
import pandas as pd
import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from historical.download_dscovr_cdaweb import (
    IngestConfig,
    aggregate_magnetic_to_one_minute,
    build_csv_request_url,
    extract_file_descriptions,
    normalize_magnetic_csv,
    normalize_plasma_csv,
    read_cdaweb_csv,
)
from historical.select_quiet_window import score_windows


def test_build_url_uses_basic_iso_and_csv():
    url = build_csv_request_url(
        "DSCOVR_H1_FC",
        ["V_GSE", "Np"],
        "2024-05-10T00:00:00Z",
        "2024-05-10T01:00:00Z",
    )
    assert "20240510T000000Z,20240510T010000Z" in url
    assert "/V_GSE,Np?format=csv" in url


def test_descriptor_parser_accepts_direct_and_wrapped_shapes():
    direct = {"FileDescription": [{"Name": "https://example/data.csv", "Length": 10}]}
    wrapped = {"DataResult": direct}
    assert extract_file_descriptions(direct)[0]["Name"].endswith("data.csv")
    assert extract_file_descriptions(wrapped)[0]["Length"] == 10


def test_csv_reader_skips_metadata_preamble():
    content = b"# generated by CDAWeb\n! another line\nEpoch,B1F1,FLAG1\n2024-05-10T00:00:00Z,5,0\n"
    frame = read_cdaweb_csv(content)
    assert list(frame.columns) == ["Epoch", "B1F1", "FLAG1"]
    assert frame.loc[0, "B1F1"] == 5


def magnetic_raw(seconds=60):
    times = pd.date_range("2024-05-10", periods=seconds, freq="s", tz="UTC")
    return pd.DataFrame(
        {
            "Epoch": times.astype(str),
            "B1GSE_1": np.full(seconds, 3.0),
            "B1GSE_2": np.full(seconds, 4.0),
            "B1GSE_3": np.zeros(seconds),
            "B1F1": np.full(seconds, 5.01),
            "FLAG1": np.zeros(seconds),
        }
    )


def test_magnetic_normalization_keeps_gse_and_diagnostic_not_filter():
    raw = magnetic_raw()
    raw.loc[0, "B1F1"] = 4.0  # diagnostic inconsistency, but source flag remains good
    frame = normalize_magnetic_csv(raw)
    assert "bx_gse" in frame.columns
    assert "bx_gsm" not in frame.columns
    assert frame.loc[0, "provider_below_vector_flag"]
    assert frame.loc[0, "quality_pass"]


def test_magnetic_minute_requires_45_good_seconds():
    frame = normalize_magnetic_csv(magnetic_raw(44))
    assert aggregate_magnetic_to_one_minute(frame).empty
    frame = normalize_magnetic_csv(magnetic_raw(60))
    minute = aggregate_magnetic_to_one_minute(frame)
    assert len(minute) == 1
    assert minute.loc[0, "coordinate_frame"] == "GSE"
    assert minute.loc[0, "valid_seconds"] == 60


def test_plasma_quality_tiers_are_preserved():
    raw = pd.DataFrame(
        {
            "Epoch": ["2024-05-10T00:00:00Z", "2024-05-10T00:01:00Z", "2024-05-10T00:02:00Z"],
            "V_GSE_X": [-400.0, -410.0, -420.0],
            "V_GSE_Y": [0.0, 0.0, 0.0],
            "V_GSE_Z": [0.0, 0.0, 0.0],
            "Np": [5.0, 6.0, 7.0],
            "THERMAL_TEMP": [100000.0, 110000.0, 120000.0],
            "DQF": [0, 2, 4],
        }
    )
    frame = normalize_plasma_csv(raw)
    assert frame.loc[0, "quality_pass"]
    assert not frame.loc[1, "quality_pass"]
    assert frame.loc[1, "nonfill_quality_pass"]
    assert not frame.loc[2, "nonfill_quality_pass"]
    assert frame.loc[0, "speed"] == 400.0


def test_quiet_selector_uses_kinetics_and_picks_quiet_window():
    times = pd.date_range("2020-04-01", periods=60 * 24 * 60, freq="min", tz="UTC")
    speed = np.full(len(times), 400.0)
    density = np.full(len(times), 5.0)
    speed[30 * 24 * 60 :] = 700.0
    frame = pd.DataFrame({"time_tag": times, "speed": speed, "density": density})
    result = score_windows(
        frame, window_days=30, stride_days=30, minimum_coverage_fraction=0.99
    )
    assert len(result) == 2
    assert result.iloc[0]["start_utc"].startswith("2020-04-01")
    assert result.iloc[0]["transient_fraction"] == 0.0
    assert result.iloc[1]["transient_fraction"] > 0.99


def test_paired_downloader_fails_closed_after_2019(tmp_path):
    from historical.download_dscovr_cdaweb import DownloadError, download_interval

    with pytest.raises(DownloadError, match="paired definitive coverage"):
        download_interval(
            "2024-05-08T00:00:00Z",
            "2024-05-15T00:00:00Z",
            tmp_path,
        )


def test_epoch_runner_imports_after_magnetic_only_split():
    import historical.run_epoch_batch as runner

    assert callable(runner.run_magnetic_only)
