# nuclear_test_correlation.yml
name: Nuclear Test Chi Correlation

on:
  schedule:
    - cron: '0 0 * * *'  # Daily run

jobs:
  correlate_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Download DOE NV-209 database
        run: |
          wget https://nnss.gov/wp-content/uploads/2023/08/DOE_NV-209_Rev16.pdf
          # Convert PDF to CSV (use tabula-py or similar)
          
      - name: Download Soviet test database
        run: |
          wget https://www.johnstonsarchive.net/nuclear/tests/USSR-ntests0.html
          # Parse HTML tables to CSV
          
      - name: Load historical chi data
        run: |
          python scripts/load_chi_historical.py
          
      - name: Correlate test dates with chi spikes
        run: |
          python scripts/correlate_nuclear_chi.py \
            --test_db data/nuclear_tests_1945_1992.csv \
            --chi_db data/historical_chi_1945_1992.csv \
            --output results/nuclear_chi_correlation.csv
          
      - name: Generate report
        run: |
          python scripts/generate_correlation_report.py
